### ISSUE TITLE
Rhs2116Headstage - Combine data streams to mirror the stimulus sequence abstraction

### ISSUE THREAD

**Issue by bparks13** [open-ephys/onix-bonsai-onix1#104] opened 2024-06-04 17:30 UTC
In issue-26-gui , the `Rhs2116StimulusSequence` is abstracted in the GUI to be a 32 channel sequence, instead of two 16 channel sequences. However, this could be confusing if the sequence is 32 channels, but each `Rhs2116Data` node only streamed 16 channels.

Therefore, before pushing the `Rhs2116StimulusSequence` changes, we need to finish the abstraction by creating a combined 32 channel `Rhs2116Data` node.

**Comment by jonnew** [comment] 2024-08-13 15:11
#122 is a duplicate of this issue. In its discussion, @glopesdev suggests a pattern that can be used to make this dual datastream device.

**Closed** 2024-08-13 15:11 UTC
Labels: feature
